spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      isolation-level: read_committed
      enable-auto-commit: false
      ### need unique group-id for each instance to reply ws connections
      group-id: notification-${random.uuid}

      #consider using String[De]Serializer and removing json mapping
      properties:
        spring.json.trusted.package: com.example.kafkastompmessaging.model
        spring.json.type.mapping: handle:com.example.kafkastompmessaging.model.NotificationMessage

#logging.level.root: INFO