spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all
#        spring.json.trusted.package: com.common
#        spring.json.type.mapping: foo:com.common.Foo,bar:com.common.Bar
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      isolation-level: read_committed
      enable-auto-commit: false
#      group-id: notificaiton-${uuid.random}
      group-id: notification
      properties:
        spring.json.trusted.package: com.example.kafkastompmessaging.model
        spring.json.type.mapping: handle:com.example.kafkastompmessaging.model.NotificationMessage

#logging.level.root: INFO